name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Setup Zig
      uses: goto-bus-stop/setup-zig@v1.2.3
      with:
        version: master
    
    - name: Run testsuite
      run: |
        zig test testsuite.zig
  
    - name: Build async example
      run: |
        zig build-exe async.zig
